# Generated by Django 3.2.24 on 2024-03-07 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='admins')),
                ('tel', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
