# Generated by Django 3.2.23 on 2024-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240307_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='encarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1', models.FileField(upload_to='pdfs/')),
                ('pdf2', models.FileField(upload_to='pdfs/')),
                ('pdf3', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
