# Generated by Django 3.2.23 on 2024-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240324_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
