# Generated by Django 3.2.23 on 2024-03-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20240325_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='observacao',
        ),
    ]
