# Generated by Django 3.2.23 on 2024-12-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_endereco_observacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
