# Generated by Django 4.2.16 on 2024-12-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bool_cpf_cnpj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_ou_cnpj',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_ou_cnpj_formatado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=19),
        ),
    ]
