# Generated by Django 4.2.16 on 2024-12-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cliente_bool_cpf_cnpj_cliente_cpf_ou_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
    ]
