# Generated by Django 4.2.16 on 2024-12-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carroproduto',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='carroproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carro',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carroproduto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
