# Generated by Django 3.2.23 on 2024-12-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_carroproduto_avaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('codigo_GTIN', models.CharField(max_length=14)),
                ('preco_unitario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_retira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(default='un', max_length=30)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='encarte',
        ),
        migrations.RemoveField(
            model_name='pedido_order',
            name='email',
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='cpf_cnpj',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='nome_cliente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_GTIN',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='desconto_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='desconto_retira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_unitario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
