# Generated by Django 4.2.16 on 2025-01-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_endereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='cliente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='endereco_envio_formatado',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='endereco_envio',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
    ]
