# Generated by Django 4.2.16 on 2025-01-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_pedido_order_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido em Andamento', 'Pedido em Andamento'), ('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completado', 'Pedido Completo'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='telefone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
