# Generated by Django 4.2.16 on 2025-01-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_pedido_order_pedido_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_order',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='pedido_order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pedido_order',
            name='total',
        ),
    ]
