# Generated by Django 4.2.16 on 2025-01-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_pedido_order_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='codigo_cliente',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='ordenado_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
