# Generated by Django 4.2.16 on 2025-01-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_pedido_order_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='telefone',
            field=models.CharField(default='', max_length=19),
        ),
    ]
