# Generated by Django 4.2.16 on 2025-01-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_pedido_order_frete_alter_pedido_order_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='forma_de_pagamento',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='local_de_pagamento',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
