# Generated by Django 4.2.16 on 2025-01-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_pedido_order_forma_de_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_order',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro'),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='endereco_envio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
    ]
