# Generated by Django 4.2.16 on 2025-01-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_pedido_order_carro_alter_pedido_order_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
