# Generated by Django 4.2.16 on 2025-01-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_pedido_order_email_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_produto',
            name='pedido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.pedido_order'),
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido em Andamento', 'Pedido em Andamento'), ('Pedido Recebido', 'Pedido Recebido'), ('Pagamento Pendente', 'Pagamento Pendente'), ('Pagamento Processando', 'Pagamento Processando'), ('Pagamento Confirmado', 'Pagamento Confirmado'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completado', 'Pedido Completo'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50),
        ),
    ]
