# Generated by Django 4.2.16 on 2025-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_pedido_produto_pedido_pedido_produto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
