# Generated by Django 4.2.16 on 2025-01-13 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_alter_pedido_produto_desconto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_produto',
            name='codigo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='codigo_GTIN',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_retira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='desconto_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='preco_unitario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='admin')),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=19)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
