# Generated by Django 4.2.16 on 2025-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_pedido_produto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin'),
        ),
    ]
