# Generated by Django 4.2.16 on 2025-01-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_admin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='visualizacao',
            new_name='quantidade_vendas',
        ),
    ]
