# Generated by Django 4.2.16 on 2025-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_visualizacao_produto_quantidade_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='visualizacao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
