# Generated by Django 4.2.16 on 2025-01-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_produto_visualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='id_PagBank',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
