# Generated by Django 4.2.16 on 2025-01-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_pedido_order_id_pagbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='status_test',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
