# Generated by Django 5.1.5 on 2025-01-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_pedido_order_status_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_estoque',
            field=models.BooleanField(default=True),
        ),
    ]
