# Generated by Django 5.1.5 on 2025-01-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_produto_em_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produtos')),
                ('produto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.produto')),
            ],
        ),
    ]
