# Generated by Django 4.2.16 on 2025-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_fotos_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido_order',
            name='status_test',
        ),
    ]
