# Generated by Django 4.2.16 on 2025-01-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_test_status_remove_pedido_order_status_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_Status',
            new_name='TestStatus',
        ),
    ]
