# Generated by Django 4.2.16 on 2025-01-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_test_status_teststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos_produto',
            name='img_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='num_fotos',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
