# Generated by Django 4.2.16 on 2025-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_fotos_produto_img_num_produto_num_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='desconto_forma_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='desconto_retirada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
