# Generated by Django 4.2.16 on 2025-02-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_pedido_order_desconto_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos_Produto',
            new_name='FotosProduto',
        ),
        migrations.AddField(
            model_name='carroproduto',
            name='subtotal_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
