# Generated by Django 4.2.16 on 2025-02-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_apikey_delete_produtoapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_produto',
            name='pedido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pedidoProduto', to='app.pedido_order'),
        ),
    ]
