# Generated by Django 4.2.16 on 2025-02-26 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_pedido_produto_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carroproduto',
            name='produto',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='cliente',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='endereco_envio',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.endereco'),
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='produto',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Categoria',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria'),
        ),
    ]
