# Generated by Django 4.2.16 on 2025-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_carroproduto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
