# Generated by Django 4.2.16 on 2025-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_produto_image_alter_produto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
