# Generated by Django 4.2.16 on 2025-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_produto_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatus',
            name='cu',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
