# Generated by Django 4.2.16 on 2025-03-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_teststatus_cu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido em Andamento', 'Pedido em Andamento'), ('Pedido Recebido', 'Pedido Recebido'), ('Pagamento Pendente', 'Pagamento Pendente'), ('Pagamento Processando', 'Pagamento Processando'), ('Pagamento Confirmado', 'Pagamento Confirmado'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Pronta Retirada', 'Pedido Pronta Retirada'), ('Pedido Completado', 'Pedido Completo'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50),
        ),
    ]
