# Generated by Django 4.2.16 on 2025-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_cliente_verificado_alter_pedido_order_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_produto',
            name='nome_produto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
