# Generated by Django 4.2.16 on 2025-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_pedido_produto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='titulo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
