# Generated by Django 4.2.16 on 2025-04-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_endereco_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='acabamento_superficial',
            field=models.CharField(blank=True, choices=[('Porcelanato', '0,0 a 0,5'), ('Grês', '0,5 a 3,0'), ('Semi Grês', '3,0 a 6,0'), ('Bllb', '6,0 a 10,0'), ('Monoporosa', '&ge;10')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='classe_tecnica_absorcao_pisos',
            field=models.CharField(blank=True, choices=[('Porcelanato', '0,0 a 0,5'), ('Grês', '0,5 a 3,0'), ('Semi Grês', '3,0 a 6,0'), ('Bllb', '6,0 a 10,0'), ('Monoporosa', '&ge;10')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='espessura',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='formato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='indicação_uso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='indicação_uso_complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='junta_minima',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='palet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='pecas_caixa',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_bruto_caixa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='relevo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
