# Generated by Django 4.2.16 on 2025-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_produto_acabamento_superficial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='indicação_uso_complemento',
        ),
        migrations.AddField(
            model_name='produto',
            name='variacao_faces',
            field=models.CharField(blank=True, choices=[('V1', 'Peças uniformes, onde a variação entre uma peça e outra não é perceptível'), ('V2', 'Leve variação, existem diferenças perceptíveis entre as peças, mas as texturas e tons apresentados são muito próximos'), ('V3', 'Variação moderada, algumas peças são diferentes umas das outras'), ('V4', 'Alta variação, as peças tem uma diferença bem significativa entre elas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='acabamento_superficial',
            field=models.CharField(blank=True, choices=[('Polido', 'Polido'), ('Brilho', 'Brilho'), ('Acetinado', 'Acetinado'), ('Granilha', 'Granilha'), ('Antiderrapante', 'Antiderrapante')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='indicação_uso',
            field=models.CharField(blank=True, choices=[('LA', 'Sem tráfego - Indicado para uso em paredes'), ('LB', 'Pouco tráfego - Indicado para uso interno, sem acesso a áreas externas, em residências'), ('LC', 'Médio tráfego - Indicado para todas as dependências residenciais e comerciais de médio tráfego'), ('LD', 'Alto tráfego - Indicado para todas as dependências residenciais e comerciais de alto tráfego')], max_length=90, null=True),
        ),
    ]
