# Generated by Django 4.2.16 on 2025-04-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_produto_indicação_uso_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classe_tecnica_absorcao_pisos',
            field=models.CharField(blank=True, choices=[('0,0 a 0,5', 'Porcelanato'), ('0,5 a 3,0', 'Grês'), ('3,0 a 6,0', 'Semi Grês'), ('6,0 a 10,0', 'Bllb'), ('>10', 'Monoporosa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='indicação_uso',
            field=models.CharField(blank=True, choices=[('Sem tráfego - Indicado para uso em paredes', 'LA'), ('Pouco tráfego - Indicado para uso interno, sem acesso a áreas externas, em residências', 'LB'), ('Médio tráfego - Indicado para todas as dependências residenciais e comerciais de médio tráfego', 'LC'), ('Alto tráfego - Indicado para todas as dependências residenciais e comerciais de alto tráfego', 'LD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='variacao_faces',
            field=models.CharField(blank=True, choices=[('Peças uniformes, onde a variação entre uma peça e outra não é perceptível', 'V1'), ('Leve variação, existem diferenças perceptíveis entre as peças, mas as texturas e tons apresentados são muito próximos', 'V2'), ('Variação moderada, algumas peças são diferentes umas das outras', 'V3'), ('Alta variação, as peças tem uma diferença bem significativa entre elas', 'V4')], max_length=121, null=True),
        ),
    ]
