# Generated by Django 4.2.16 on 2025-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_produto_classe_tecnica_absorcao_pisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classe_tecnica_absorcao_pisos',
            field=models.CharField(blank=True, choices=[('0,0 a 0,5', 'Porcelanato'), ('0,5 a 3,0', 'Grês'), ('3,0 a 6,0', 'Semi Grês'), ('6,0 a 10,0', 'Bllb'), ('>10', 'Monoporosa')], max_length=50, null=True),
        ),
    ]
