# Generated by Django 4.2.16 on 2025-04-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_produto_classe_tecnica_absorcao_pisos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='indicação_uso',
            new_name='indicacao_uso',
        ),
    ]
