# Generated by Django 4.2.16 on 2025-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_rename_indicação_uso_produto_indicacao_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_estoque_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
