# Generated by Django 4.2.16 on 2025-04-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_produto_em_estoque_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='em_estoque_list',
        ),
    ]
