# Generated by Django 4.2.16 on 2025-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_produto_em_estoque_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_lojas',
            field=models.ManyToManyField(blank=True, related_name='estoqueLojas', to='app.endereco'),
        ),
    ]
