# Generated by Django 4.2.16 on 2025-04-25 20:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_produto_estoque_lojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='em_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_lojas',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_lojas',
            field=models.JSONField(default=app.models.estoque_loja),
        ),
    ]
