# Generated by Django 4.2.16 on 2025-04-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_produto_em_estoque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_order',
            name='ordenado_por',
        ),
    ]
