# Generated by Django 4.2.16 on 2025-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_rename_pedido_order_pedidoorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=19, null=True),
        ),
    ]
