# Generated by Django 4.2.16 on 2025-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_admin_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
