# Generated by Django 4.2.16 on 2025-05-22 18:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_admin_email_alter_admin_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosproduto',
            name='image',
            field=models.ImageField(upload_to=app.models.user_upload_path),
        ),
    ]
