# Generated by Django 4.2.16 on 2025-05-22 19:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_fotosproduto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosproduto',
            name='image',
            field=models.ImageField(unique=True, upload_to=app.models.user_upload_path),
        ),
    ]
