# Generated by Django 4.2.16 on 2025-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_fotosproduto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoorder',
            name='order_PagBank',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
