# Generated by Django 4.2.16 on 2025-06-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_pedidoorder_order_pagbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('erro_code', models.CharField(blank=True, max_length=10, null=True)),
                ('erro_message', models.CharField(blank=True, max_length=200, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro')),
                ('cliente', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
