# Generated by Django 4.2.16 on 2025-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_rename_adminlogs_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='ocorrido_em',
            field=models.DateTimeField(),
        ),
    ]
