# Generated by Django 4.2.16 on 2025-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_adminlog_ocorrido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='ocorrido_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
