# Generated by Django 4.2.16 on 2025-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_banner_position_alter_adminlog_ocorrido_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesquisa', models.CharField(default='', max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
