# Generated by Django 4.2.16 on 2025-06-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_logpesquisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logpesquisa',
            old_name='data',
            new_name='ocorrido_em',
        ),
    ]
